--- 
framework: 
  AdminMode: 0
  ApplicationClass: Qublog
  ApplicationName: Qublog
  ApplicationUUID: 79CA768A-3C86-11DD-AF3C-232A75D5E9C0
  ConfigFileVersion: 4
  Database: 
    AutoUpgrade: 1
    CheckSchema: 1
    Database: qublog
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.4.1
  DevelMode: 1
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - LetMe: {} 
    - SkeletonApp: {} 
    - REST: {} 
    - Halo: {} 
    - ErrorTemplates: {} 
    - OnlineDocs: {} 
    - CompressedCSSandJS: {} 
    - AdminUI: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 1
  TemplateClass: Qublog::View
  View: 
    FallbackHandler: Jifty::View::Mason::Handler
    Handlers: 
      - Jifty::View::Static::Handler
      - Jifty::View::Declare::Handler
      - Jifty::View::Mason::Handler
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates

application:
  none_project_name: none

  salt_hash:
    digest: SHA-512
